### ISSUE TITLE
error: Class 'App\Providers\MailchimpTool' not found

### ISSUE THREAD

**Issue by jayenne** [naifalshaye/mailchimp#1]
Hi Naif, i've followed the instructions and get this error: Class 'App\Providers\MailchimpTool' not found.

Any thoughts what I've missed or done wrong?

thanks.

*laravel 5.8 +Nova +Spark

**Comment by naifalshaye** [comment]
You just need to import the class. I don't see any other issues.

**Comment by evelynDickinson** [comment]
Same issue. 

Laravel 6.2

Composer installed fine, edited env, and NovaServiceProvider tools function to import the class; new MailchimpTool()
